import { LEFT_RIGHT_LAYOUT_CONFIG, SIDEBAR_FOLD_WIDTH, SIDEBAR_OPEN_WIDTH } from './default-layout-config';

const DEFAULT_LAYOUT_CONFIG = LEFT_RIGHT_LAYOUT_CONFIG;

export { DEFAULT_LAYOUT_CONFIG, SIDEBAR_OPEN_WIDTH, SIDEBAR_FOLD_WIDTH };
